### ISSUE TITLE
Gem name: "will_paginate-bootstrap5", usage: require "will_paginate-bootstrap4"

### ISSUE THREAD

**Issue by kevinmtrowbridge** [delef/will_paginator-bootstrap5#1]
It's not a huge deal, it's just a little misleading. If the require statement CAN be different from the gem name, perhaps it would be best named simply: ""will_paginate-bootstrap."  Thanks for your library!

**Comment by delef** [comment]
@kevinmtrowbridge that's good advice, thank you.
